### PR TITLE
Fix `:scope` selector implementation for cases with self-node selector

### LINKED ISSUE #42: `:scope` (I guess) breaks normal `querySelector`
Microsoft Edge.

```html
<div class="parent">
  <p class="child">
  </p>
</div>
```

Without DOM4:

```javascript
document.querySelector('.parent').querySelector('.child') // OK
document.querySelector('.parent').querySelector('.parent > .child') // OK
document.querySelector('.parent').querySelector('> .child') // Syntax Error
document.querySelector('.parent').querySelector(':scope > .child') // Syntax Error
```

With DOM4:

```javascript
document.querySelector('.parent').querySelector('.child') // OK
document.querySelector('.parent').querySelector('.parent > .child') // null
document.querySelector('.parent').querySelector('> .child') // OK
document.querySelector('.parent').querySelector(':scope > .child') // OK
```

### PR DESCRIPTION
**Pull request by AlexWayfer**
Also set and remove `data-scope-*` attribute instead of temporary `id` replacing,
which can broke some styles or external code for miliseconds.

Resolve #42

### CODE REVIEW

**Comment by WebReflection** [comment]
thanks! are you sure data attributes in CSS are compatible with the list of this polyfill targets?
https://github.com/WebReflection/dom4#compatibility

**Comment by AlexWayfer** [comment]
> are you sure data attributes in CSS are compatible with the list of this polyfill targets?
https://github.com/WebReflection/dom4#compatibility

I don't know how to check :( But all browsers can work with `data-*` attributes via `getAttribute` and other fucntions. I think, they can work with any attribute at all, also in CSS, `foo` for example.

New browsers can use `dataset`, but they always could use `getAttribute`: https://caniuse.com/#feat=dataset

And also I found: `data-*` attributes, as `foo`, will be invalid for HTML4: https://stackoverflow.com/a/1735268/2630849

But they should work.

And I think this is better then `id` replacement, on which developers can relay, in their CSS or parallel JS (and `id = undefined` (if there was not id) in JS make `id=""` in HTML).

**Comment by WebReflection** [comment]
quickly replying, sorry:

  * the question was: are those browsers compatible with `[data-scope=3456789]` CSS selector? 
  * the id was left untouched before ... added only if not already present so it was absolutely unobtrusive (no issues with what you mentioned) and it was working as CSS selector with every target browser

**Comment by AlexWayfer** [comment]
I'll try to install Windows 7 into VirtualBox and check.

> the question was: are those browsers compatible with [data-scope=3456789] CSS selector?

Selector is `data-scope-3456789`, without value :wink: And numbers are allowed in attribute name. And `getAttribute` should work. And CSS, I guess, too.

> the id was left untouched before ... added only if not already present so it was absolutely unobtrusive (no issues with what you mentioned) and it was working as CSS selector with every target browser

Oh, yes, sorry.

**Comment by WebReflection** [comment]
why do you keep mentioning `getAttribute` that has nothing to do with this ticket or the question about CSS selectors ? 😄 does `document.querySelector("[data-scope-3456789]")` works in all target browsers?

can we just go back to the ID that has been tested in all target browsers? or the fix does not work if we go back to ID ? how about a one-off runtime class instead ?

**Comment by AlexWayfer** [comment]
> why do you keep mentioning getAttribute that has nothing to do with this ticket or the question about CSS selectors ?

Because this changes uses `getAttribute`, and because I think CSS-selectors by custom attribute works where `getAttribute` works.

> does document.querySelector("[data-scope-3456789]") works in all target browsers?

Does this library works in target browsers at all? :grimacing: 

image

> can we just go back to the ID that has been tested in all target browsers?

Yes, we can. But I'm already not sure that this was tested. And I think it's ugly. But we can.

> or the fix does not work if we go back to ID ?

No, they works.

> how about a one-off runtime class instead ?

What? Work with `class` attribute? Without `classList` it can be painful, but maybe.

**Comment by AlexWayfer** [comment]
Fixed (and works) for IE8:

image

Pay attention to replacing `HTMLElement` with `Element`.

1. There is no `HTMLElement` in IE8 (compatibillity, about which you're so worried, was broken in some cases because of it)
2. `querySelector(|All)` is [methods of `Element`](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelector), not [`HTMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement#Methods)

**Comment by AlexWayfer** [comment]
Oh, I should remove/replace `> -1` after `findInResult`, sorry.

**Comment by WebReflection** [comment]
Yes, some test is not for IE but that’s all documented . All devices in the list also have been tested for real. Some of them won’t show 100% green but that’s also documented

**Comment by AlexWayfer** [comment]
> Oh, I should remove/replace > -1 after findInResult, sorry.

Done.

> All devices in the list also have been tested for real. 

I don't know how to test in Blackberry 7.1, for example, or in Nokia Xpress Browser. But I think if in IE8 it works — it'll work almost everywhere.

**Comment by WebReflection** [comment]
> But I think if in IE8 it works — it'll work almost everywhere.

very wrong assumptions, older webkit are the worst but I've researched a little bit and `[attr]` selector seems to be fine.

It'd be great if you could drop that misleading bit about the `id` from the commit message but since I won't have time later on I'll merge this as it is.

Thanks for your patience.

**Comment by AlexWayfer** [comment]
> It'd be great if you could drop that misleading bit about the id from the commit message but since I won't have time later on I'll merge this as it is.

Sorry :( My bad.

> very wrong assumptions, older webkit are the worst but I've researched a little bit and [attr] selector seems to be fine.

I'm trying to install Android 2.1 now in emulator, and I'll report if something will go wrong.

**Pull request merged**
