### PR TITLE
DocumentFragment should have append method.

### PR DESCRIPTION
**Pull request by mk0x9**
According to [spec][1] `DocumentFragment` implements `ParentNode` interface, yet polyfill doesn't account for that.

```javascript
> 'append' in document.createDocumentFragment();
< false
```

[1]: https://dom.spec.whatwg.org/#interface-parentnode

### CODE REVIEW

**Comment by mk0x9** [comment]
Should I write additional test cases?

Also, why you catching exception in case if mutating `document.createDocumentFragment().prototype` fails? Where this could happen?

**Comment by WebReflection** [comment]
Thanks for the report. I'll answer to everything at once in here:

  1. please do not modify manually anything inside the `build` folder. Just modify the file into the `src` one. If you want to PR properly run `make dependencies` and after that just run `make`
  2. in the [following list of devices](https://github.com/WebReflection/dom4#compatibility) there were edge cases covered by the try catch. This should not bother you at all so I don't see the problem in having it there. The idea is to limit compatibility issues when this file is in. Removing the try catch won't give you any advantage so please leave it as it is now ;-)
  3. your check is obtrusive. You are testing that the property is either append or prepend but you are nto checking if the engine already implements native those two methods. You should temporarily grab the prototype and verify it doesn't have already those two methods and only if that's true you can add them

I might just quickly patch this so don't worry about this if you don't have time and thanks again for bringing this up.

**Comment by mk0x9** [comment]
Thanks for extensive reply. I'm wondering about try/catch because this polyfill deployed on our mobile site (which is having millions of unique users). So compatibility is the issue though we don't pursue support of outdated user agents. So not really important, just got my attention.

> You are testing that the property is either append or prepend but you are nto checking if the engine already implements native those two methods.

Yup, that's true! I'll fix it on the weekend.

**Comment by WebReflection** [comment]
no need to fix anything, the version `1.7.0` has everything you need plus tests ;-)

**Comment by WebReflection** [comment]
FYI the commit with all needed changes is here: https://github.com/WebReflection/dom4/commit/11c0275a70691ee323839346c003e79711d4c002

I've done few little extra adjustments too plus added tests

**Comment by mk0x9** [comment]
Great, thanks! :-)

**Pull request closed without merging**
